groups:
- name: cleanup
  jobs:
  - delete-deployments-fresh
  - delete-deployments-upg1
  - delete-deployments-upg2
  - cleanup-resources

resources:
- name: postgres-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: develop

jobs:
- name: delete-deployments-fresh
  serial_groups: [cleanup]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release
  - task: delete-diego-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      DEPLOYMENT_NAME: pgci-cf-diego
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
  - task: delete-cf-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      DEPLOYMENT_NAME: {{cf_deployment}}
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}

- name: delete-deployments-upg1
  serial_groups: [cleanup]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release
      passed: [delete-deployments-fresh]
      trigger: true
  - task: delete-diego-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      DEPLOYMENT_NAME: {{upg1_diego_deployment}}
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
  - task: delete-cf-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      DEPLOYMENT_NAME: {{upg1_cf_deployment}}
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}

- name: delete-deployments-upg2
  serial_groups: [cleanup]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release
      passed: [delete-deployments-upg1]
      trigger: true
  - task: delete-diego-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      DEPLOYMENT_NAME: {{upg2_diego_deployment}}
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
  - task: delete-cf-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      DEPLOYMENT_NAME: {{upg2_cf_deployment}}
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}

- name: cleanup-resources
  serial_groups: [cleanup]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release
      passed: [delete-deployments-upg2]
      trigger: true
  - task: cleanup-releases
    file: postgres-release/ci/scripts/run-bosh-cleanup/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
