resources:
- name: postgres-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: develop

jobs:
- name: delete-deployments-postgres
  serial_groups: [cleanup]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release
  - task: delete-pg-master-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params: &base_params
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
      DEPLOYMENT_NAME: {{master_pg_deployment}}
  - task: delete-pg-old-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      <<: *base_params
      DEPLOYMENT_NAME: {{old_pg_deployment}}

- name: delete-deployments-cf-diego
  serial_groups: [cleanup]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release
      passed: [delete-deployments-postgres]
      trigger: true
  - task: delete-diego-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      <<: *base_params
      DEPLOYMENT_NAME: {{fresh_diego_deployment}}
  - task: delete-cf-old-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      <<: *base_params
      DEPLOYMENT_NAME: {{fresh_cf_deployment}}
  - task: delete-diego-old-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      <<: *base_params
      DEPLOYMENT_NAME: {{old_diego_deployment}}
  - task: delete-cf-old-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      <<: *base_params
      DEPLOYMENT_NAME: {{old_cf_deployment}}
  - task: delete-diego-older-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      <<: *base_params
      DEPLOYMENT_NAME: {{older_diego_deployment}}
  - task: delete-cf-older-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      <<: *base_params
      DEPLOYMENT_NAME: {{older_cf_deployment}}

- name: cleanup-resources
  serial_groups: [cleanup]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release
      passed: [delete-deployments-cf-diego]
      trigger: true
  - task: cleanup-releases
    file: postgres-release/ci/scripts/run-bosh-cleanup/task.yml
    params:
      <<: *base_params
