groups:
- name: postgres
  jobs:
  - deploy-with-cf
  - deploy-with-diego

resources:
- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: develop

- name: postgres-release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: develop

- name: postgres-ci-env
  type: git
  source:
    uri: git@github.com:cloudfoundry/postgres-ci-env
    branch: master
    private_key: {{postgres_ci_env_private_key}}

- name: diego-release-master
  type: git
  source:
    branch: master
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry/diego-release.git

jobs:
- name: deploy-with-cf
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: cf-release
    - get: postgres-ci-env
    - get: postgres-release
      resource: postgres-release-develop
  - task: deploy-with-cf
    file: postgres-release/ci/scripts/deploy-with-cf/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
      CF_DEPLOYMENT_TRACE: true

- name: deploy-with-diego
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: postgres-ci-env
    - get: diego-release
      resource: diego-release-master
    - get: postgres-release
      resource: postgres-release-develop
      passed: [deploy-with-cf]
      trigger: true
  - task: deploy-with-diego
    file: postgres-release/ci/scripts/deploy-with-diego/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
