groups:
- name: postgres-upgrade
  jobs:
  - deploy-with-cf-upg1
  - deploy-with-diego-upg1
#  - populate-db-upg1
  - upgrade-cf-upg1
#  - check-db-upg1
  - delete-deployments

resources:
- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: develop

- name: postgres-release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: develop

- name: postgres-ci-env
  type: git
  source:
    uri: git@github.com:cloudfoundry/postgres-ci-env
    branch: master
    private_key: {{postgres_ci_env_private_key}}

jobs:
- name: deploy-with-cf-upg1
  serial_groups: [postgres-upgrade]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
    - get: postgres-ci-env
  - task: deploy-with-cf-old
    file: postgres-release/ci/scripts/deploy-with-cf-old/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
      OLD_CF_RELEASE: 231
      CF_DEPLOYMENT: {{upg1_cf_deployment}}
      API_USER: {{upg1_api_user}}
      API_PASSWORD: {{upg1_api_password}}
- name: deploy-with-diego-upg1
  serial_groups: [postgres-upgrade]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
      passed: [deploy-with-cf-upg1]
      trigger: true
    - get: postgres-ci-env
  - task: deploy-with-diego-old
    file: postgres-release/ci/scripts/deploy-with-diego-old/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
      OLD_CF_RELEASE: 231
      OLD_DIEGO_RELEASE: 0.1460.0
      OLD_GARDEN_RELEASE: 0.334.0
      OLD_ETCD_RELEASE: 38
      CF_DEPLOYMENT: {{upg1_cf_deployment}}
      DIEGO_DEPLOYMENT: {{upg1_diego_deployment}}
#- name: populate-db-upg1
#  serial_groups: [postgres-upgrade]
#  plan:
#  - aggregate:
#    - get: postgres-ci-env
#      passed: [deploy-with-diego-upg1]
#      trigger: true
#  - task: populate-db
#    file: postgres-release/ci/scripts/populate-db/task.yml
#    params:
#      API_ENDPOINT: api.apps.{{upg1_cf_deployment}}.microbosh
#      API_USER: {{upg1_api_user}}
#      API_PASSWORD: {{upg1_api_password}}
- name: upgrade-cf-upg1
  serial_groups: [postgres-upgrade]
  plan:
  - aggregate:
    - get: cf-release
    - get: postgres-ci-env
    - get: postgres-release
      resource: postgres-release-develop
      #passed: [populate-db-upg1]
      passed: [deploy-with-diego-upg1]
      trigger: true
  - task: deploy-with-cf
    file: postgres-release/ci/scripts/deploy-with-cf/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
      HAPROXY_DEPLOYMENT: none
      CF_DEPLOYMENT: {{upg1_cf_deployment}}
      API_USER: {{upg1_api_user}}
      API_PASSWORD: {{upg1_api_password}}
#- name: check-db-upg1
#  serial_groups: [postgres-upgrade]
#  plan:
#  - aggregate:
#    - get: postgres-ci-env
#      passed: [upgrade-cf-upg1]
#      trigger: true
#  - task: check-db
#    file: postgres-release/ci/scripts/check-db/task.yml
#    params:
#      API_ENDPOINT: api.apps.{{upg1_cf_deployment}}.microbosh
#      API_USER: {{upg1_api_user}}
#      API_PASSWORD: {{upg1_api_password}}
- name: delete-deployments
  serial_groups: [postgres-update]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
#      passed: [check-db-upg1]
      passed: [upgrade-cf-upg1]
      trigger: true
  - task: delete-diego-deployment
    file: postgres-release/ci/scripts/run-bosh-command/task.yml
    params:
      DEPLOYMENT_NAME: {{upg1_diego_deployment}}
      COMMAND: delete deployment {{upg1_diego_deployment}}
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
  - task: delete-cf-deployment
    file: postgres-release/ci/scripts/run-bosh-command/task.yml
    params:
      DEPLOYMENT_NAME: {{upg1_cf_deployment}}
      COMMAND: delete deployment {{upg1_cf_deployment}}
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
#  - task: cleanup-releases
#    file: postgres-release/ci/scripts/run-bosh-cleanup/task.yml
#    params:
#      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
#      BOSH_USER: {{postgres_cf_bosh_user}}
#      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
