groups:
- name: release-upgrade
  jobs:
  - deploy-master-postgres
  - load-postgres-db
  - upgrade-master-postgres
  - check-postgres-db
  - delete-deployment-master
  - cleanup-resources

resources:
- name: postgres-release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: develop

- name: postgres-ci-env
  type: git
  source:
    uri: git@github.com:cloudfoundry/postgres-ci-env
    branch: master
    private_key: {{postgres_ci_env_private_key}}

- name: postgres-release-master
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: master

jobs:
- name: deploy-master-postgres
  serial_groups: [deploy,master]
  plan:
  - aggregate:
    - get: postgres-ci-env
    - get: postgres-release
      resource: postgres-release-develop
  - task: deploy-postgres
    file: postgres-release/ci/scripts/deploy-postgres/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
      PG_DEPLOYMENT: pgci-master
      PG_VERSION: master
      PG_USER: {{pg_user}}
      PG_PSW: {{pg_password}}
      PG_PORT: 5524
      PG_DB: {{pg_db}}

- name: load-postgres-db
  serial_groups: [master]
  plan:
  - aggregate:
    - get: postgres-ci-env
    - get: postgres-release
      resource: postgres-release-develop
      passed: [deploy-master-postgres]
      trigger: true
  - task: load-postgres-db
    file: postgres-release/ci/scripts/load-postgres-db/task.yml
    params:
      PG_USER: {{pg_user}}
      PG_PSW: {{pg_password}}
      PG_HOST: 0.postgres.default.pgci-master.microbosh
      PG_PORT: 5524
      PG_DB: {{pg_db}}

- name: upgrade-master-postgres
  serial_groups: [deploy,master]
  plan:
  - aggregate:
    - get: postgres-ci-env
    - get: postgres-release
      resource: postgres-release-develop
      passed: [load-postgres-db]
      trigger: true
  - task: deploy-latest-postgres
    file: postgres-release/ci/scripts/deploy-postgres/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
      PG_DEPLOYMENT: pgci-master
      PG_VERSION: develop
      PG_USER: {{pg_user}}
      PG_PSW: {{pg_password}}
      PG_PORT: 5524
      PG_DB: {{pg_db}}

- name: check-postgres-db
  serial_groups: [master]
  plan:
  - aggregate:
    - get: postgres-ci-env
    - get: postgres-release
      resource: postgres-release-develop
      passed: [upgrade-master-postgres]
      trigger: true
  - task: check-postgres-db
    file: postgres-release/ci/scripts/check-postgres-db/task.yml
    params:
      PG_USER: {{pg_user}}
      PG_PSW: {{pg_password}}
      PG_HOST: 0.postgres.default.pgci-master.microbosh
      PG_PORT: 5524
      PG_DB: {{pg_db}}

- name: delete-deployment-master
  serial_groups: [master,deploy]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
      passed: [check-postgres-db]
      trigger: true
  - task: delete-postgres-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      DEPLOYMENT_NAME: pgci-master
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}

- name: cleanup-resources
  serial_groups: [cleanup]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
      passed: [delete-deployment-master]
      trigger: true
  - task: cleanup-releases
    file: postgres-release/ci/scripts/run-bosh-cleanup/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
